//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace OPPF.XML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/Config.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/Config.xsd", IsNullable=false)]
    public partial class Config {
        
        private string loggerConfigField;
        
        private string archiveDirField;
        
        private string webDirField;
        
        private string xmlDirField;
        
        private string doneDirField;
        
        private string wsPlateEndpointField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string imageBaseUrlField;
        
        private string dbConnectionStringField;
        
        private string dbQueryStringField;
        
        private string lightPathEndpointField;

        private string sampleLocationEndpointField;
        
        /// <remarks/>
        public string LoggerConfig {
            get {
                return this.loggerConfigField;
            }
            set {
                this.loggerConfigField = value;
            }
        }
        
        /// <remarks/>
        public string ArchiveDir {
            get {
                return this.archiveDirField;
            }
            set {
                this.archiveDirField = value;
            }
        }
        
        /// <remarks/>
        public string WebDir {
            get {
                return this.webDirField;
            }
            set {
                this.webDirField = value;
            }
        }
        
        /// <remarks/>
        public string XmlDir {
            get {
                return this.xmlDirField;
            }
            set {
                this.xmlDirField = value;
            }
        }
        
        /// <remarks/>
        public string DoneDir {
            get {
                return this.doneDirField;
            }
            set {
                this.doneDirField = value;
            }
        }
        
        /// <remarks/>
        public string WsPlateEndpoint {
            get {
                return this.wsPlateEndpointField;
            }
            set {
                this.wsPlateEndpointField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ImageBaseUrl {
            get {
                return this.imageBaseUrlField;
            }
            set {
                this.imageBaseUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DbConnectionString {
            get {
                return this.dbConnectionStringField;
            }
            set {
                this.dbConnectionStringField = value;
            }
        }
        
        /// <remarks/>
        public string DbQueryString {
            get {
                return this.dbQueryStringField;
            }
            set {
                this.dbQueryStringField = value;
            }
        }
        
        /// <remarks/>
        public string LightPathEndpoint {
            get {
                return this.lightPathEndpointField;
            }
            set {
                this.lightPathEndpointField = value;
            }
        }

        /// <remarks/>
        public string SampleLocationEndpoint
        {
            get
            {
                return this.sampleLocationEndpointField;
            }
            set
            {
                this.sampleLocationEndpointField = value;
            }
        }
    }
}
